/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.marcinchwedczuk.bzzz;

import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

public class App {
    public static void main(String[] args) throws InterruptedException {

    }
}
