/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.marcinchwedczuk.bzzz;

import pl.marcinchwedczuk.bzzz.gui.MainWindow;

public class App {
    public static void main(String[] args) throws InterruptedException {
        MainWindow.main(args);
    }
}
